# spring
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    #url: jdbc:mysql://livestream.ctdvxjsmcmyj.us-east-2.rds.amazonaws.com:3306/livestream?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    url: jdbc:mysql://localhost:3306/livestream?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
  # liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.xml
    drop-first: false
  jpa:
    properties:
      hibernate:
        open-in-view: false # disable this anti pattern
#          show_sql: true
#          format_sql: true
      show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy/MM/dd HH:mm
  mvc:
    favicon:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail.smtp.starttls.enable: true

# Application config
application:
  enable-security: true # be careful when use this config

# Task
cron-job:
  daily-update-data:
    time: 0 0 7 * * ? # 7h00AM

# Email
email:
  receiver: kientt@rabiloo.com

server:
  servlet:
    session:
      timeout: 1d
  port: 8081
rtmp-server:
  streamer: rtmp://localhost:1935/live
  client: http://localhost:8080/hls/
firebase:
  file-key: /home/ngocnd/Downloads/livestreampj-ab132-firebase-adminsdk-tizfw-528540be76.json
  database-url: https://livestreampj-ab132.firebaseio.com

